version: '3.1'

services:
  php:
    build: ./php
    ports:
      - 8081:80

  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080